apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdbclaim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  volumeName: postgresdb
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresinitclaim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  volumeName: postgresinit
  resources:
    requests:
      storage: 1Gi
  