apiVersion: v1
kind: Service
metadata:
  # use this as the host name to connect to postgres db
  name: postgresdb
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
