kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresinit
spec:
  capacity:
    storage: 1Gi
  azureFile:
    secretName: azure-secret
    shareName: k8sflaskpostgresinit
    secretNamespace: null
  accessModes:
    - ReadOnlyMany
  storageClassName: azurefile
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl