apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdbclaim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresinitclaim
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: azurefile
  volumeName: postgresinit
  resources:
    requests:
      storage: 1Gi
  