apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdbclaim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  volumeName: az-storage
  resources:
    requests:
      storage: 1Gi
  