apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: {{ .Values.registryname }}
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "12G"
        #     cpu: "2000m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acrregistrykey
      